window.HOLIDAY_COLLECTIONS = Object.freeze([
  {
    slug: "the-winter-cottage",
    spotsRemaining: 1,
    name: "The Winter Cottage",
    date: "October 24",
    shortDate: "Oct 24",
    time: "11:30 AM to 2:30 PM",
    location: "The Cottage · Indoors",
    feeling: "Soft · Snowy · Intimate · Timeless",
    description: "A soft, snowy little cottage in ivory and powder blue. Frosted trees, cozy textures, a fireplace, and quiet Christmas-morning details make this feel peaceful, warm, and easy to settle into.",
    think: "Cream, ivory, pale blue, oatmeal, soft knits, linen, cashmere, and subtle winter layers.",
    accent: "#b8c7cf",
    image: "assets/winter-cottage.webp",
    imageAlt: "Pale blue and white Christmas cottage living room with a chandelier, frosted tree, and soft neutral furnishings",
    imagePosition: "center 52%",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/The-Winter-Cottage"
  },
  {
    slug: "pine-plaid",
    spotsRemaining: 0,
    name: "Pine + Plaid",
    date: "October 24",
    shortDate: "Oct 24",
    time: "2:30 PM to 5:00 PM",
    location: "The Cottage · Outdoors",
    feeling: "Nostalgic · Playful · Heritage · Classic",
    description: "A vintage-inspired Christmas with the feeling of a classic J.Crew holiday campaign. Plaid, pine, wool, and heritage Americana set the scene, with real snow play outside for the kids.",
    think: "Plaid, denim, forest green, navy, red, camel, corduroy, wool sweaters, boots, and layered outerwear.",
    experienceTitle: "Little Winter Magic",
    experienceDescription: "Yes, there will be snow. A snow machine (using soap) will create a little winter moment for the kids. All the fun of pretending Miami actually turned into a snowy Christmas morning.",
    accent: "#485b45",
    image: "assets/pine-plaid.webp",
    imageAlt: "Outdoor Christmas tree with plaid details, wrapped gifts, and evergreens",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/Pine-Plaid"
  },
  {
    slug: "home-for-christmas",
    spotsRemaining: 0,
    publicPath: "/home-for-christmas",
    name: "Home for Christmas",
    date: "November 7",
    shortDate: "Nov 7",
    time: "11:00 AM to 4:30 PM",
    location: "Mint Studios",
    feeling: "Warm · Cozy · Nostalgic · Home",
    description: "A cozy Christmas-at-home scene wrapped in cream, deep burgundy, candlelight, evergreen, soft bedding, and the quiet magic of Christmas morning. Warm, intimate, and made to feel like home.",
    think: "Cream, deep burgundy, evergreen, soft knits, pajamas, velvet, tartan, and cozy holiday layers.",
    experienceTitle: "The Christmas Gift",
    experienceDescription: "Families will wrap their session Polaroid and Christmas ornament together to take home as The Christmas Gift.",
    accent: "#7d2027",
    image: "assets/home-for-christmas.webp",
    imageAlt: "Cozy Christmas bedroom with children resting on a bed, burgundy bows, candlelight, evergreen garland, and a decorated tree",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/homeforchristmas"
  },
  {
    slug: "christmas-bound",
    spotsRemaining: 0,
    name: "Christmas Bound",
    date: "November 15",
    shortDate: "Nov 15",
    time: "3:00 PM to 5:00 PM",
    location: "Vintage Car Event · 4 sessions",
    feeling: "Cinematic · Adventurous · Nostalgic · Homeward",
    description: "A Christmas journey inspired by the feeling of heading home for the holidays. Luggage, packages, trees, and vintage travel details turn the trip itself into part of the Christmas story.",
    think: "Tartan, denim, corduroy, wool coats, sweaters, loafers, boots, and lived-in layers.",
    accent: "#8f3030",
    image: "assets/christmas-bound.webp",
    imageAlt: "Vintage red convertible filled with wrapped Christmas gifts, wreaths, and evergreen trees",
    imagePosition: "center 62%",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/Christmas-Bound"
  },
  {
    slug: "chestnut-christmas",
    spotsRemaining: 2,
    name: "Chestnut Christmas",
    date: "November 21",
    shortDate: "Nov 21",
    time: "11:00 AM to 4:30 PM",
    location: "Mint Studios",
    feeling: "Warm · Heritage · Classic · Cozy",
    description: "Warm brown tones, wood, books, plaid, and natural textures bring an old-fashioned Christmas-at-home feeling to the set. Cozy, lived-in, and quietly polished.",
    think: "Chocolate, camel, cream, forest green, tartan, wool, corduroy, loafers, and knits.",
    experienceTitle: "The Christmas Card",
    experienceDescription: "Families will use the Polaroid from their session to create The Christmas Card and take it home.",
    accent: "#74513f",
    image: "assets/chestnut-christmas.webp",
    imageAlt: "Warm cream Christmas living room with chestnut ornaments, brown velvet bows, evergreen garland, and layered neutral furnishings",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/Chestnut-Christmas"
  },
  {
    slug: "the-winter-carousel",
    spotsRemaining: 0,
    name: "The Winter Carousel",
    date: "November 22",
    shortDate: "Nov 22",
    time: "1:30 PM to 3:30 PM",
    location: "Mint Studios",
    feeling: "Dreamy · Whimsical · Playful · Magical",
    description: "A little Christmas magic made for the kids. Frosted trees, a beautiful carousel, and plenty of room to ride, play, and be little create a session built around childhood wonder.",
    think: "Ivory, winter white, soft neutrals, delicate textures, and timeless children’s clothing.",
    accent: "#c5b996",
    image: "assets/winter-carousel.webp",
    imageAlt: "White and gold winter carousel surrounded by frosted Christmas trees",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/The-Winter-Carousel"
  },
  {
    slug: "coastal-christmas",
    spotsRemaining: 0,
    publicPath: "/coastal-christmas",
    name: "A Coastal Christmas",
    date: "November 28",
    shortDate: "Nov 28",
    time: "3:00 PM to 5:00 PM",
    location: "Outdoor Coastal Story",
    feeling: "Coastal · Warm · Relaxed · Miami",
    description: "A very Miami Christmas. A beautiful white cottage surrounded by warm sand, soft neutrals, natural pine, and coastal details gives traditional Christmas a South Florida point of view without turning it into a beach theme.",
    think: "Cream, oatmeal, sage, dusty blue, sand, linen, soft knits, natural textures, and understated holiday details.",
    accent: "#819189",
    image: "assets/salt-pine.webp",
    imageAlt: "South Florida Christmas courtyard with a white cottage, warm sand, natural pine, and soft coastal holiday details",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/coastal-christmas"
  }
].map(Object.freeze));
