window.HOLIDAY_COLLECTIONS = Object.freeze([
  {
    slug: "the-winter-cottage",
    name: "The Winter Cottage",
    date: "October 24",
    shortDate: "Oct 24",
    time: "11:30 AM to 2:30 PM",
    price: 595,
    location: "The Cottage · Indoors",
    feeling: "Soft · Intimate · Wintery · Timeless",
    description: "A quiet winter morning tucked away at the cottage. Soft whites, icy blues, natural wood, snowy trees, and candlelight create a peaceful Christmas setting made for connection and soft, lived-in moments.",
    think: "Cream, ivory, pale blue, oatmeal, soft knits, linen, cashmere, and subtle winter layers.",
    accent: "#b8c7cf",
    image: "assets/winter-cottage.webp",
    imageAlt: "Soft neutral Christmas cottage interior with a tree, fireplace, and natural winter layers",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/The-Winter-Cottage"
  },
  {
    slug: "pine-plaid",
    name: "Pine + Plaid",
    date: "October 24",
    shortDate: "Oct 24",
    time: "2:30 PM to 5:00 PM",
    price: 650,
    location: "The Cottage · Outdoors",
    feeling: "Nostalgic · Playful · Woodsy · Classic",
    description: "Christmas heads outdoors with evergreens, tartan, layered knits, wrapped gifts, and the easy energy of a classic holiday catalog. Less standing still. More decorating, laughing, moving, and being together.",
    think: "Plaid, denim, forest green, navy, red, camel, corduroy, wool sweaters, boots, and layered outerwear.",
    accent: "#485b45",
    image: "assets/pine-plaid.webp",
    imageAlt: "Outdoor Christmas tree with plaid details, wrapped gifts, and evergreens",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/Pine-Plaid"
  },
  {
    slug: "a-crimson-christmas",
    name: "A Crimson Christmas",
    date: "November 7",
    shortDate: "Nov 7",
    time: "11:00 AM to 4:30 PM",
    price: 595,
    location: "Mint Studios",
    feeling: "Rich · Traditional · Romantic · Grand",
    description: "Deep crimson, evergreen, candlelight, velvet bows, and all the richness of a traditional Christmas dressed up for the occasion. Classic holiday color made dramatic, warm, and timeless.",
    think: "Burgundy, deep red, black, evergreen, cream, velvet, tartan, and holiday dresswear.",
    accent: "#7d2027",
    image: "assets/crimson-christmas.webp",
    imageAlt: "Deep crimson and evergreen traditional Christmas room glowing with candlelight",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/A-Crimson-Christmas"
  },
  {
    slug: "velvet-december",
    name: "Velvet December",
    date: "November 8",
    shortDate: "Nov 8",
    time: "2:00 PM to 4:30 PM",
    price: 595,
    location: "Mint Studios",
    feeling: "Romantic · Artistic · Vintage · Soft",
    description: "A softer take on Christmas, filled with dusty rose, muted blue, antique gold, velvet ribbon, and collected details. It feels like opening a box of Christmas treasures that has been kept for years.",
    think: "Mauve, dusty blue, cream, velvet, satin, delicate patterns, and antique-inspired pieces.",
    accent: "#9b7580",
    image: "assets/velvet-december.webp",
    imageAlt: "Soft mauve and dusty blue Christmas living room with restrained vintage details",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/Velvet-December"
  },
  {
    slug: "little-women",
    name: "Little Women",
    date: "November 14",
    shortDate: "Nov 14",
    time: "1:00 PM to 3:00 PM",
    price: 650,
    location: "Limited Holiday Story",
    feeling: "Romantic · Literary · Nostalgic · Intimate",
    description: "Inspired by the warmth and romance of Christmases from another time, Little Women is quiet, sentimental, and beautifully old-fashioned. Think simple traditions, soft fabrics, candlelight, handwritten letters, ribbons, and the kind of Christmas that feels handmade rather than decorated.",
    think: "Cream, faded florals, burgundy, forest green, lace, linen, wool, ribbons, vintage silhouettes, and heirloom-inspired pieces.",
    accent: "#6f594c",
    image: "assets/little-women.webp",
    imageAlt: "Warm old-fashioned Christmas fireside room with stockings, plaid, and handmade details",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/Little-Women"
  },
  {
    slug: "christmas-bound",
    name: "Christmas Bound",
    date: "November 15",
    shortDate: "Nov 15",
    time: "3:00 PM to 5:00 PM",
    price: 650,
    location: "Vintage Car Event · 4 sessions",
    feeling: "Cinematic · Adventurous · Nostalgic · Cool",
    description: "Pack the presents, grab the tree, and pile into the car. Christmas Bound turns the holiday road trip into a vintage editorial, filled with evergreen, layered winter styling, and the feeling that somewhere wonderful is waiting ahead.",
    think: "Tartan, denim, corduroy, wool coats, sweaters, loafers, boots, and lived-in layers.",
    accent: "#8f3030",
    image: "",
    imageAlt: "",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/Christmas-Bound"
  },
  {
    slug: "chestnut-christmas",
    name: "Chestnut Christmas",
    date: "November 21",
    shortDate: "Nov 21",
    time: "11:00 AM to 4:30 PM",
    price: 595,
    location: "Mint Studios",
    feeling: "Warm · Heritage · Classic · Cozy",
    description: "Warm chestnut tones, traditional greenery, rich plaids, natural textures, and a beautifully lived-in feeling. Relaxed and polished at once, with the warmth of a classic holiday campaign.",
    think: "Chocolate, camel, cream, forest green, tartan, wool, corduroy, loafers, and knits.",
    accent: "#74513f",
    image: "assets/chestnut-christmas.webp",
    imageAlt: "Warm chestnut brown and cream Christmas living room with classic greenery",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/Chestnut-Christmas"
  },
  {
    slug: "the-winter-carousel",
    name: "The Winter Carousel",
    date: "November 22",
    shortDate: "Nov 22",
    time: "1:30 PM to 3:30 PM",
    price: 595,
    location: "Mint Studios",
    feeling: "Dreamy · Whimsical · Elegant · Magical",
    description: "Frosted trees, winter whites, soft gold, and an old-fashioned carousel create a Christmas dream that feels magical without becoming overly sweet. A little world made for childhood wonder.",
    think: "Ivory, winter white, soft neutrals, delicate textures, and timeless children’s clothing.",
    accent: "#c5b996",
    image: "assets/winter-carousel.webp",
    imageAlt: "White and gold winter carousel surrounded by frosted Christmas trees",
    bookingUrl: "https://ECCreativeStudio.pixieset.com/booking/The-Winter-Carousel"
  },
  {
    slug: "salt-pine",
    name: "Salt + Pine",
    date: "November 28",
    shortDate: "Nov 28",
    time: "3:00 PM to 5:00 PM",
    price: 650,
    location: "Outdoor Coastal Story",
    feeling: "Coastal · Warm · Relaxed · Nostalgic · Natural",
    description: "A Christmas story made for Miami. Salt + Pine brings the warmth of the holidays outdoors with soft sand, natural pine, warm ivory tones, woven textures, and the glow of late afternoon light. It feels relaxed and coastal without becoming beachy, giving you the nostalgia of Christmas at home with a distinctly South Florida point of view.",
    think: "Cream, oatmeal, sage, dusty blue, sand, linen, soft knits, natural textures, and understated holiday details.",
    accent: "#819189",
    image: "assets/salt-pine.webp",
    imageAlt: "South Florida Christmas courtyard with palms, warm light, and a softly decorated tree",
    bookingUrl: ""
  }
].map(Object.freeze));

